#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: fetch-os-proj <proj-number>"
    exit 1
fi

# some vars
proj_name="cs439t_f24_p${1}_goppert"
proj_dir="${HOME}/439/${proj_name}"

# clone
git clone ssh://git@git.gheith.com:22/${proj_name} ${proj_dir}

# to be, or not to be
if [ -d "$proj_dir" ]; then
    # can i be #1?
    cd $HOME/439/$proj_name
    touch spamon
    for file in t0*; do cp "$file" "goppert${file:2}"; done
    git add . && git commit -m "spamon" && git push
    exit 0
else
    # :/
    echo "ERR: FAILED TO FIND CLONED PROJECT"
fi
