#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: loop-fetch <proj-number>"
    exit 1
fi

while true
do
    fetch-os-proj ${1}
    if [ $? -eq 0 ]; then
        echo "GOT"
        exit 0
    else
        echo "FAILED; TRYING AGAIN"
        sleep 1s
    fi
done
