#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: proj-pull <proj-number>"
    exit 1
fi

proj_name="cs439t_f24_p$1_goppert"
clone_cmd="git clone ssh://git@git.gheith.com:22/$proj_name $HOME/439/$proj_name"
$clone_cmd
cd $HOME/439/$proj_name
touch spamon
for file in t0*; do cp "$file" "goppert${file:2}"; done
git add . && git commit -m "spamon" && git push
